# Generated by Django 5.0.2 on 2025-09-23 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, choices=[('baku', 'Baku'), ('ganja', 'Ganja'), ('sumgait', 'Sumgait'), ('agsu', 'Agsu'), ('shamakhi', 'Shamakhi'), ('salyan', 'Salyan'), ('shirvan', 'Shirvan'), ('khachmaz', 'Khachmaz'), ('shaki', 'Shaki'), ('nakhchivan', 'Nakhchivan'), ('lankaran', 'Lankaran'), ('masalli', 'Masalli')], default='agsu', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snowboard_subcategory', models.CharField(blank=True, choices=[('helmet', 'Helmet'), ('bindings', 'Bindings'), ('goggles', 'Goggles'), ('snowboard_boots', 'Snowboard Boots'), ('snowboard_jacket', 'Snowboard Jacket'), ('gloves', 'Gloves'), ('snowboard_pants', 'Snowboard pants'), ('layers', 'Layers'), ('snowboard_googles', 'Snowboard Goggles'), ('jacket', 'Jacket'), ('backpack', 'Backpack')], default='helmet', max_length=42, null=True)),
                ('box_equipment_subcategory', models.CharField(blank=True, choices=[('boxing_gloves', 'Boxing Gloves'), ('boxing_shoes', 'Boxing Shoes'), ('hand_wraps', 'Hand Wraps'), ('punching_bags', 'Punching bags'), ('heavy_bag', 'Heavy Bag'), ('jump_rope', 'Jump Rope'), ('headgear', 'Headgear'), ('speed_bags', 'Speed bags'), ('hanging_punch', 'Hanging Punch'), ('double_end_bag', 'Double End Bag')], default='boxing_gloves', max_length=42, null=True)),
                ('golf_equipment_subcategory', models.CharField(blank=True, choices=[('putters', 'Putters'), ('woods', 'Woods'), ('irons', 'Irons'), ('hybrids', 'Hybrids'), ('wedges', 'Wedges'), ('driver', 'Driver'), ('golf_clubs', 'Golf Clubs'), ('tees', 'Tees'), ('golf_shoes', 'Golf Shoes'), ('marker', 'Marker')], default='putters', max_length=42, null=True)),
                ('tennis_equipment_subcategory', models.CharField(blank=True, choices=[('putters', 'Putters'), ('woods', 'Woods'), ('irons', 'Irons'), ('hybrids', 'Hybrids'), ('wedges', 'Wedges'), ('driver', 'Driver'), ('golf_clubs', 'Golf Clubs'), ('tees', 'Tees'), ('golf_shoes', 'Golf Shoes'), ('marker', 'Marker')], default='tennis_balls', max_length=42, null=True)),
                ('school_equipment_subcategory', models.CharField(blank=True, choices=[('erasers', 'Erasers'), ('backpack', 'Backpack'), ('glue_sticks', 'Glue Sticks'), ('pencil_sharpener', 'Pencil Sharpener'), ('ruler', 'Ruler'), ('scissors', 'Scissors'), ('crayons', 'Crayons'), ('folders', 'Folders'), ('highlighters', 'Highlighters'), ('markers', 'Markers')], default='erasers', max_length=42, null=True)),
                ('fruit_subcategory', models.CharField(blank=True, choices=[('apple', 'Apple'), ('apricot', 'Apricot'), ('banana', 'Banana'), ('canary_melon', 'Canary Melon'), ('cherry', 'Cherry'), ('watermelon', 'Watermelon'), ('currants', 'Currants'), ('grape', 'Grape'), ('kiwi', 'Kiwi'), ('dragon_fruit', 'Dragon Fruit')], default='apple', max_length=42, null=True)),
                ('vegetable_subcategory', models.CharField(blank=True, choices=[('carrot', 'Carrot'), ('broccoli', 'Broccoli'), ('cabbage', 'Cabbage'), ('cauliflower', 'Cauliflower'), ('spinach', 'Spinach'), ('cucumber', 'Cucumber'), ('eggplant', 'Eggplant'), ('onion', 'Onion'), ('peas', 'Peas'), ('artichoke', 'Artichoke')], default='carrot', max_length=42, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Elan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lalafo.comment')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lalafo.location')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lalafo.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to='lalafo.comment')),
                ('elan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elan_likes', to='lalafo.elan')),
            ],
        ),
    ]
