# Generated by Django 5.0.2 on 2025-09-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lalafo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='elan',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='elan',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='elan',
            name='is_vip',
            field=models.BooleanField(default=False),
        ),
    ]
