# Generated by Django 5.0.2 on 2025-09-23 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lalafo', '0002_elan_is_active_elan_is_premium_elan_is_vip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to='lalafo.comment'),
        ),
        migrations.AlterField(
            model_name='like',
            name='elan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elan_likes', to='lalafo.elan'),
        ),
    ]
