# Generated by Django 5.0.2 on 2025-09-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lalafo', '0003_alter_like_comment_alter_like_elan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elan',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
