# Generated by Django 5.0.2 on 2025-09-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lalafo', '0004_alter_elan_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elan',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
